# Generated by Django 2.2.2 on 2019-06-06 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppl_order_tracking', '0003_auto_20190606_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemsarrived',
            old_name='date_recieved',
            new_name='date_received',
        ),
    ]
