# Generated by Django 2.2.2 on 2019-06-24 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppl_order_tracking', '0004_auto_20190606_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsarrived',
            name='po_number',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='ppl_order_tracking.PurchaseOrder'),
        ),
    ]
